# Generated by Django 6.0.8 on 2026-08-06 06:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('default_unit', models.CharField(blank=True, max_length=6, verbose_name='usual unit')),
                ('category', models.CharField(blank=True, choices=[('produce', 'fruit and vegetables'), ('dairy', 'dairy and eggs'), ('meat', 'meat and fish'), ('bakery', 'bread and baking'), ('dry', 'store cupboard'), ('spice', 'herbs and spices'), ('frozen', 'frozen'), ('drink', 'drinks'), ('other', 'other')], help_text='Used to group a shopping list.', max_length=10, verbose_name='category')),
                ('note', models.CharField(blank=True, help_text='e.g. “the one in the blue bag”, “only the Italian”.', max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='also called')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='pantry.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'other name',
                'verbose_name_plural': 'other names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='amount')),
                ('unit', models.CharField(blank=True, max_length=6, verbose_name='unit')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='note')),
                ('checked_at', models.DateTimeField(auto_now=True, verbose_name='last checked')),
                ('ingredient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='in_pantry', to='pantry.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'pantry item',
                'verbose_name_plural': 'pantry',
                'ordering': ['ingredient__name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=9, verbose_name='amount')),
                ('unit', models.CharField(blank=True, max_length=6, verbose_name='unit')),
                ('label', models.CharField(blank=True, help_text='e.g. “bag”, “bottle”, “block”.', max_length=60, verbose_name='sold as')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_sizes', to='pantry.ingredient', verbose_name='ingredient')),
            ],
            options={
                'verbose_name': 'purchase size',
                'verbose_name_plural': 'purchase sizes',
                'ordering': ['amount'],
                'constraints': [models.UniqueConstraint(fields=('ingredient', 'amount', 'unit'), name='one_row_per_purchase_size')],
            },
        ),
    ]
