# Generated by Django 6.0.8 on 2026-08-06 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='enabled',
            field=models.BooleanField(default=False, help_text='With this off, the local password form is the only way in.', verbose_name='offer single sign-on'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='groups_claim',
            field=models.CharField(default='groups', help_text='The claim the group names arrive in. Some providers send none at all.', max_length=100, verbose_name='group claim'),
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timer_sound', models.CharField(choices=[('chime', 'chime — two soft notes'), ('bell', 'bell — one long ring'), ('beeps', 'beeps — three short tones'), ('alarm', 'alarm — insistent, for a noisy kitchen'), ('none', 'no sound')], default='chime', help_text='Played when a step’s timer reaches nought.', max_length=10, verbose_name='timer sound')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'preferences',
                'verbose_name_plural': 'preferences',
            },
        ),
    ]
