# Generated by Django 6.0.8 on 2026-08-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_ssoconfiguration_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssoconfiguration',
            name='endpoints_read_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ssoconfiguration',
            name='request_timeout',
            field=models.PositiveSmallIntegerField(default=10, help_text='Seconds to wait for the provider before giving up.', verbose_name='request timeout'),
        ),
        migrations.AlterField(
            model_name='ssoconfiguration',
            name='op_base',
            field=models.URLField(blank=True, help_text='The issuer, e.g. https://sso.example.org — or paste the full …/.well-known/openid-configuration address if that is what your provider gives you.', max_length=500, verbose_name='SSO server'),
        ),
    ]
