# Generated by Django 6.0.8 on 2026-08-09 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_ssoconfiguration_endpoints_read_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SSOIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True, verbose_name='subject')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('matched_by_email', models.BooleanField(default=False, help_text='Attached to an account that already existed, rather than creating one.', verbose_name='matched by e-mail address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_identity', to=settings.AUTH_USER_MODEL, verbose_name='account')),
            ],
            options={
                'verbose_name': 'provider identity',
                'verbose_name_plural': 'provider identities',
            },
        ),
    ]
