# Generated by Django 6.0.8 on 2026-08-04 20:46

import apps.recipes.images
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, unique=True)),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('description', models.TextField(blank=True, help_text='One or two sentences — what this is, and when you would make it.', verbose_name='description')),
                ('servings', models.PositiveSmallIntegerField(default=4, verbose_name='servings')),
                ('prep_minutes', models.PositiveIntegerField(blank=True, help_text='In minutes.', null=True, verbose_name='preparation time')),
                ('cook_minutes', models.PositiveIntegerField(blank=True, help_text='In minutes.', null=True, verbose_name='cooking time')),
                ('instructions', models.TextField(blank=True, verbose_name='instructions')),
                ('image', models.ImageField(blank=True, upload_to=apps.recipes.images.recipe_image_path, verbose_name='photograph')),
                ('source', models.CharField(blank=True, help_text='A person, a cookbook, a magazine.', max_length=200, verbose_name='source')),
                ('source_url', models.URLField(blank=True, max_length=500, verbose_name='link')),
                ('notes', models.TextField(blank=True, help_text='What you would do differently next time.', verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipes', to=settings.AUTH_USER_MODEL, verbose_name='added by')),
                ('tags', models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'recipe',
                'verbose_name_plural': 'recipes',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=3, max_digits=9, null=True, verbose_name='amount')),
                ('unit', models.CharField(blank=True, max_length=30, verbose_name='unit')),
                ('name', models.CharField(max_length=120, verbose_name='ingredient')),
                ('note', models.CharField(blank=True, help_text='e.g. “finely chopped”, “at room temperature”.', max_length=120, verbose_name='note')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'ingredient',
                'verbose_name_plural': 'ingredients',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['-created_at'], name='recipe_newest_idx'),
        ),
    ]
