# Generated by Django 6.0.8 on 2026-08-05 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='alternative_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alternatives', to='recipes.recipeingredient', verbose_name='alternative for'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='optional',
            field=models.BooleanField(default=False, help_text='The recipe works without it.', verbose_name='optional'),
        ),
        migrations.CreateModel(
            name='CookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooked_at', models.DateTimeField(auto_now_add=True, verbose_name='cooked on')),
                ('servings_made', models.PositiveSmallIntegerField(default=1, verbose_name='servings made')),
                ('minutes', models.PositiveIntegerField(blank=True, help_text='In minutes. Measured by the cooking view, or typed in.', null=True, verbose_name='time taken')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('cooked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cook_logs', to=settings.AUTH_USER_MODEL, verbose_name='cooked by')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cook_logs', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'cooking',
                'verbose_name_plural': 'cookings',
                'ordering': ['-cooked_at'],
            },
        ),
        migrations.CreateModel(
            name='CookPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('large', 'large portion'), ('regular', 'portion'), ('small', 'small portion'), ('child', 'child’s portion'), ('togo', 'portion to take away')], max_length=10, verbose_name='size')),
                ('count', models.PositiveSmallIntegerField(default=0, verbose_name='how many')),
                ('log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portions', to='recipes.cooklog')),
            ],
            options={
                'verbose_name': 'portion',
                'verbose_name_plural': 'portions',
                'ordering': ['size'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('text', models.CharField(max_length=120, verbose_name='step')),
                ('detail', models.TextField(blank=True, help_text='Shown in the cooking view when this step is the current one.', verbose_name='detail')),
                ('minutes', models.PositiveIntegerField(blank=True, help_text='In minutes. Offers a timer while cooking.', null=True, verbose_name='duration')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='recipes.recipestep', verbose_name='feeds into')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipe')),
            ],
            options={
                'verbose_name': 'step',
                'verbose_name_plural': 'steps',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredients', to='recipes.recipestep', verbose_name='used in'),
        ),
        migrations.AddIndex(
            model_name='cooklog',
            index=models.Index(fields=['recipe', '-cooked_at'], name='cooklog_recent_idx'),
        ),
        migrations.AddConstraint(
            model_name='cookportion',
            constraint=models.UniqueConstraint(fields=('log', 'size'), name='one_row_per_portion_size'),
        ),
    ]
