# Generated by Django 6.0.8 on 2026-08-06 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipeingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='span_from',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='span_to',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
