# Generated by Django 6.0.8 on 2026-08-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipestep_span_from_recipestep_span_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='oven_celsius',
            field=models.PositiveSmallIntegerField(blank=True, help_text='In °C.', null=True, verbose_name='oven temperature'),
        ),
        migrations.AddField(
            model_name='recipestep',
            name='oven_mode',
            field=models.CharField(blank=True, max_length=12, verbose_name='oven mode'),
        ),
        migrations.AlterField(
            model_name='recipestep',
            name='text',
            field=models.TextField(verbose_name='step'),
        ),
    ]
