# Generated by Django 6.0.8 on 2026-08-08 11:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_recipestep_oven_celsius_recipestep_oven_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipestep',
            name='seconds',
            field=models.PositiveSmallIntegerField(blank=True, help_text='On top of the minutes, for a step measured more finely than that.', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='seconds'),
        ),
    ]
