# Generated by Django 6.0.8 on 2026-08-09 12:56, plus the data half by hand.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.db.models import F


def adopt_existing_recipes(apps, schema_editor):
    """Every recipe already in the collection keeps answering to its author.

    Without this the column arrives NULL on rows that predate it and
    ``views._may_edit`` — which reads ``owner`` and nothing else — turns the
    whole existing collection staff-only in one deployment. Nobody would report
    it as a migration: it presents as "Edit disappeared from my own recipes".

    One UPDATE, no Python loop over the rows: this is the first migration that
    will run against a database with the household's real recipes in it (see
    OPEN-ITEMS.md §2), and the version that pulls every row into memory is the
    one that behaves differently there than it does here.
    """
    Recipe = apps.get_model("recipes", "Recipe")
    Recipe.objects.filter(owner__isnull=True, created_by__isnull=False).update(
        owner=F("created_by"),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipestep_seconds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_recipes', to=settings.AUTH_USER_MODEL, verbose_name='looked after by'),
        ),
        # Backwards is a no-op: the column itself is removed by reversing the
        # AddField above, so there is nothing to undo and nothing to restore.
        migrations.RunPython(adopt_existing_recipes, migrations.RunPython.noop),
    ]
